---
- name: Install arch qemu packages
  community.general.pacman:
    name:
      - qemu
      - virt-manager
      - virt-viewer
      - dnsmasq
      - vde2
      - bridge-utils
      - openbsd-netcat
      - libguestfs
    state: present
  when: ansible_distribution == 'Archlinux'

- name: Install quickemu dependencies
  community.general.pacman:
    name:
      - edk2-ovmf
      - ld-lsb
      - spice-gtk
    state: present
  when: ansible_distribution == 'Archlinux'

- name: Create VM directory
  ansible.builtin.file:
    path: "{{vm_directory}}"
    state: directory
    recurse: true
    owner: "{{username}}"
    attributes: C
