---
- hosts: all
  vars:
    username: mathematician314
  roles:
    - cli
    - games
    - fish
    - slack
    - browsers
    - work
    - development
    - qemu
    - docker
    - hardware
    - graphics
    - net
    - cleanup
    - aur
    - syncthing
