---
- hosts: all
  vars:
    username: mathematician314
    user_home: /home/mathematician314
    bin_folder: /home/mathematician314/bin
  tasks:
    - name: Create bin folder
      file:
        owner: "{{ username }}"
        path: "{{ bin_folder }}"
        state: directory
  roles:
    - common
    - personal-projects
    - work-projects
    - desktop
    #    - finance
    - emacs
