---
- hosts: all
  vars:
    username: fstaffa
    user_home: "/Users/fstaffa/"
    fnm_nodejs_versions: ["latest-v12.x"]
    fnm_npm_global_packages:
      - name: fx
      - name: lodash
  tasks:
    - name: Define bins folder
      set_fact:
        bin_folder: "{{ user_home }}/data/bin"
    - name: Create bin folder
      file:
        owner: "{{ username }}"
        path: "{{ bin_folder }}"
        state: directory
    - include_role:
        name: osx
    - include_role:
        name: common

