---
- hosts: all
  vars:
    username: fstaffa
    user_home: "/Users/fstaffa/"
  tasks:
    - name: Define bins folder
      set_fact:
        bin_folder: "{{ user_home }}/bin"
    - name: Create bin folder
      file:
        owner: "{{ username }}"
        path: "{{ bin_folder }}"
        state: directory
  roles:
    - common
    - personal-projects
    - work-projects
