---
- hosts: all
  vars:
    username: mathematician314
  tasks:
    - name: Get user from passwd database
      getent:
        database: passwd
        key: "{{ username }}"
        split: ":"
    - name: Define user_home
      set_fact:
        user_home: "{{ getent_passwd[username][4] }}"
    - name: Define bins folder
      set_fact:
        bin_folder: "{{ user_home }}/bin"
    - name: Create bin folder
      file:
        owner: "{{ username }}"
        path: "{{ bin_folder }}"
        state: directory
    - include_role:
        name: common
    - include_role:
        name: development
    - include_role:
        name: work
