---

- name: Enable classic snaps
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Add slack snap
  community.general.snap:
    name: slack
    classic: yes
