---
- name: Install ubuntu emacs build prerequisites packages
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Checkout emacs
  when: false
  include_role:
    name: git-clone
  vars:
    dest: "{{ user_home }}/data/emacs-source"
    email: "294522+fstaffa@users.noreply.github.com"
    repo: https://git.savannah.gnu.org/git/emacs.git

- name: Create dotfiles folder
  file:
    owner: "{{ username }}"
    path: "{{ user_home }}/.dotfiles"
    state: directory

- name: Checkout chemacs
  git:
    repo: https://github.com/plexus/chemacs2.git
    dest: "{{ user_home }}/.emacs.d"

- name: Install doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    depth: 1
    dest: "{{ user_home }}/.dotfiles/doom-emacs"
    version: master

- name: Install spacemacs emacs
  git:
    repo: https://github.com/syl20bnr/spacemacs.git
    depth: 1
    dest: "{{ user_home }}/.dotfiles/spacemacs"
    version: develop

- name: Install doom config
  include_role:
    name: git-clone
  vars:
    dest: "{{ user_home }}/data/personal/{{ item.folder }}"
    repo: "{{ item.repo }}"
  loop:
    - repo: git@github.com:fstaffa/dotdoom.git
      folder: doom.d
