---
- name: Install emacs dependencies
  apt:
    pkg:
      - libtiff-dev
      - build-essential
      - libgtk-3-dev
      - libtiff5-dev
      - libgif-dev
      - libjpeg-dev
      - libpng-dev
      - libxpm-dev
      - libncurses-dev
      - autoconf
      - texinfo
      - libgnutls28-dev
      - libgccjit0
      - libgccjit-9-dev
      - libjansson4
      - libjansson-dev
