---
- name: Add repo for Ubuntu Focal
  apt:
   deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04" 

- name: Install dotnet sdk 5
  apt:
    pkg: dotnet-sdk-5.0