---
- include: dotnet-ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add vscode snap
  community.general.snap:
    name: code
    classic: yes
  when: ansible_distribution == 'Archlinux'
