---
- include_tasks: git-repo.yml
  loop:
    - {
        repo: git@gitlab.com:Cimpress-Technology/labe/calendars-ui.git,
        folder: calendars-ui,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/vltava-squad/ccm-next.git,
        folder: ccm,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/Sapidus/configuration-service.git,
        folder: configuration-service,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/Sapidus/deployment.git,
        folder: deployment-sapidus,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/Sapidus/logistics-configuration-ui.git,
        folder: logistics-configuration-ui,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/vltava-squad/pickups-aggregation-service.git,
        folder: picky,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/praguematic/planning-api-service.git,
        folder: planning-api,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/praguematic/pup-scraper-service.git,
        folder: pup-scraper-service,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/Sapidus/Quoter-Publisher.git,
        folder: quoter-publisher,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/labe/shipping-calculator.git,
        folder: shipping-calculator,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/praguematic/shipping-options-service.git,
        folder: shippping-options,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/qp/shipping-recommendation.git,
        folder: shiprec,
      }
    - {
        repo: git@gitlab.com:Cimpress-Technology/vltava-squad/vltava-infrastructure.git,
        folder: vltava-infrastructure,
      }
