---
- name: Check if repo exists
  stat:
    path: "{{ user_home }}/data/cimpress/{{ item.folder }}"
  register: result
- name: Checkout repo
  git:
    repo: "{{ item.repo }}"
    dest: "{{ user_home }}/data/cimpress/{{ item.folder }}"
  when: not result.stat.exists
- name: Git config
  community.general.git_config:
    name: user.email
    value: fstaffa@cimpress.com
    scope: local
    repo: "{{ user_home }}/data/cimpress/{{ item.folder }}"
