---
- name: Install ubuntu packages
  apt:
    pkg:
      - libpq-dev
      - postgresql-client-12
  when: ansible_distribution == 'Ubuntu'

- name: Install arch packages
  community.general.pacman:
    name:
      - postgresql-libs
    state: present
  when: ansible_distribution == 'Archlinux'
