---
- name: Create data folder
  file:
    path: "{{ bin_folder }}"
    state: directory

- name: Install doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    depth: 1
    dest: "{{ user_home }}/.emacs.d"
    version: develop

- name: Install doom config
  include_tasks: git-repo.yml
  loop:
    - repo: git://github.com/fstaffa/dotdoom.git
      folder: "{{ user_home }}/.doom.d"
      update: false


- name: Chezmoi init
  shell:
    cmd: |
      chezmoi init git@github.com:fstaffa/dotfiles.git
  args:
    creates: "{{ user_home }}/.local/share/chezmoi/dot_tmux.conf"
- name: Ensure chezmoi folder
  file:
    path: "{{user_home}}/.config/chezmoi"
    state: directory
- name: Chezmoi config
  copy:
    dest: "{{user_home}}/.config/chezmoi/chezmoi.toml"
    content: |
      encryption = "gpg"
      [gpg]
        symmetric = true

- name: Set global git settings
  community.general.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - key: "user.name"
      value: "Filip Staffa"
    - key: "user.email"
      value: "294522+fstaffa@users.noreply.github.com"
    - key: "pull.ff"
      value: only
    - key: "core.editor"
      value: vim
    - key: "init.defaultBranch"
      value: master
