---
# tasks file for common
- name: Install utilities
  apt:
    pkg:
      - aspell
      - aria2
      - bat
      - curl
      - fzf
      - fasd
      - ffmpeg
      - git
      - jq
      - keychain
      - lftp
      - net-tools
      - python3
      - silversearcher-ag
      - python3-pip
      - python3-venv
      - tmux
      - xdg-utils

- name: Set user settings
  user:
    name: "{{ username }}"
    shell: /usr/bin/fish

- name: Install fnm dependencies utilities
  apt:
    pkg:
      - unzip
      - curl
      - xz-utils
      - netbase

- name: Install fish repository
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install fnm dependencies utilities
  apt:
    pkg:
      - fish

- name: Set fish as default shell
  user:
    name: "{{ username }}"
    shell: /usr/bin/fish
