---
# tasks file for common
- name: Install utilities
  apt:
    pkg:
      - aspell
      - aria2
      - bat
      - curl
      - direnv
      - fzf
      - fasd
      - ffmpeg
      - git
      - jq
      - keychain
      - lftp
      - net-tools
      - python3
      - python3-pip
      - python3-venv
      - silversearcher-ag
      - tmux
      - xdg-utils

- name: Set user settings
  user:
    name: "{{ username }}"
    shell: /usr/bin/fish

- name: Install ripgrep from github
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb

- name: Install fish repository
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Install fish
  apt:
    pkg:
      - fish

- name: Set fish as default shell
  user:
    name: "{{ username }}"
    shell: /usr/bin/fish
