---
- name: Define fnm_root
  set_fact:
    fnm_root: "{{ user_home }}/.fnm"
  when: fnm_root is not defined

- name: Install fnm
  shell:
    cmd: |
      curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | \
        bash -s -- --skip-shell --install-dir {{ bin_folder }}
    executable: /bin/bash
  args:
    creates: "{{ fnm_root }}"

- name: Add fnm link to user bin
  file:
    src: "{{ fnm_root }}/fnm"
    dest: "{{ user_home }}/bin/fnm"
    state: link

- name: Install nodejs via fnm
  shell:
    cmd: |
      set -o pipefail
      eval "`fnm env`"
      fnm install {{ item }}
    executable: /bin/bash
  environment:
    PATH: "{{ fnm_root  }}:{{ ansible_env.PATH }}"
    FNM_DIR: "{{ fnm_root }}"
  register: fnm_results
  changed_when: "'successfully downloaded' in fnm_results.stdout"
  with_items: "{{ fnm_nodejs_versions }}"

- debug:
    msg: Fnm root {{ fnm_root }}

- name: Define fnm_default_nodejs_version
  set_fact:
    fnm_default_nodejs_version: "{{ fnm_nodejs_versions|first }}"
  when:
    - fnm_set_default_nodejs_ver|default(true)
    - fnm_default_nodejs_version is not defined

- name: Set default nodejs version via fnm
  shell:
    cmd: |
      set -o pipefail
      eval "`fnm env --multi`"
      fnm use {{ fnm_default_nodejs_version }}
      fnm default $(node --version)
    executable: /bin/bash
  environment:
    PATH: "{{ fnm_root  }}:{{ ansible_env.PATH }}"
    FNM_DIR: "{{ fnm_root }}"
  args:
    creates: "{{ fnm_root }}/aliases/default/bin"
  when:
    - fnm_set_default_nodejs_ver|default(true)

- name: Definde default_nodejs_path
  set_fact:
    fnm_default_nodejs_path: "{{ fnm_nodejs_versions|first }}"

- name: Install nodejs js modules
  npm:
    name: "{{ item.name }}"
    global: true
    version: "{{ item.version|default('latest') }}"
  environment:
    PATH: "{% if item.nodejs_version is defined %}{{ fnm_root }}/node-versions/v{{ item.nodejs_version }}/installation/bin{% else %}{{ fnm_root }}/node-versions/{{ fnm_default_nodejs_path }}/installation/bin{% endif %}:{{ ansible_env.PATH }}" # noqa 204
  with_items: "{{ fnm_npm_global_packages }}"
