---
- stat: path="{{ item.folder }}"
  register: repo_stat

- name: Checkout repo
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.folder }}"
  when: not repo_stat.stat.exists

- name: Git config
  community.general.git_config:
    name: user.email
    value: 294522+fstaffa@users.noreply.github.com
    scope: local
    repo: "{{ user_home }}/data/personal/{{ item.folder }}"
