---
- name: Install brew packages
  become: true
  become_user: "{{username}}"
  community.general.homebrew:
    name:
      - aspell
      - aria2
      - bat
      - fasd
      - fzf
      - git
      - gnupg
      - go
      - hugo
      - ipfs
      - jid
      - jq
      - lftp
      - openssl
      - openssl@1.1
      - p7zip
      - pipenv
      - pyenv
      - python
      - readline
      - rtv
      - eqnxio/cimpress-cloud-engineering/stskeygen
      - postgresql
      - tealdeer
      - terraform
      - tokei
      - tmux
      - the_silver_searcher
      - vegeta
      - wtfutil

- name: Install brew cask packages
  become: true
  become_user: "{{username}}"
  community.general.homebrew:
    install_options:
      - cask
    name:
      - google-chrome
      - dropbox
      - emacs
      - firefox
      - iterm2
      - jetbrains-toolbox
      - postman
      - syncthing
      - vlc
      - visual-studio-code
      - wireshark
