---
- name: Install brew
  shell:
    cmd: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: "/usr/local/bin/brew"
- name: Install brew packages
  become: true
  become_user: "{{username}}"
  homebrew:
    name:
      - aspell
      - aria2
      - bat
      - fasd
      - fzf
      - git
      - gnupg
      - go
      - hugo
      - jid
      - jq
      - lftp
      - openssl
      - openssl@1.1
      - p7zip
      - pipenv
      - pyenv
      - python
      - readline
      - rtv
      - eqnxio/cimpress-cloud-engineering/stskeygen
      - postgresql
      - tealdeer
      - terraform
      - tokei
      - tmux
      - the_silver_searcher
      - vegeta
      - wtfutil

- name: Install brew cask packages
  become: true
  become_user: "{{username}}"
  homebrew_cask:
    name:
      - aws-vault
      - google-chrome
      - dropbox
      - emacs
      - firefox
      - iterm2
      - jetbrains-toolbox
      - postman
      - steam
      - syncthing
      - vagrant
      - vlc
      - visual-studio-code
      - virtualbox
      - virtualbox-extension-pack
      - wireshark

- name: Enable fish shell
  lineinfile:
    path: /etc/shells
    regexp: "/usr/local/bin/fish"
    line: "/usr/local/bin/fish"

- name: Make fish shell
  user:
    name: fstaffa
    shell: /usr/local/bin/fish
