---
- name: Update packages & caches
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install syncthing
  community.general.pacman:
    name:
      - syncthing
    state: present

- name: Enable syncthing systemd service
  ansible.builtin.systemd:
    state: started
    name: syncthing@{{username}}.service
    enabled: yes
