name: Yaml Lint
on: [push]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prettier-lint
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: "**/*.{yml,yaml,md} --write"
          dry: true
